### PR TITLE
add ; for systemverilog

### PR DESCRIPTION
**Pull request by sqlmap3**

### CODE REVIEW

**Comment by junegunn** [comment]
For putting multiple statements in a single-line?

**Comment by sqlmap3** [comment]
bit a;
bit[2047:0] b;   
 then 
bit            &#160; &#160;&#8195;  &#8195; &#8195; &#8195; a;
bit[2047:0] &#160; &nbsp; &#8195; b;

**Comment by junegunn** [comment]
And the suggested rule gives

```
bit a               ;
bit[2047:0] b       ;
then
bit            a    ;
bit[2047:0]       b ;
```

I'm not familar with the language but this doesn't look good to me. Is this really what you want?

**Comment by sqlmap3** [comment]
image

modfited it;
image

**Comment by junegunn** [comment]
I see, but judging from other code snippets I see on the internet, it doesn't look like the alignment style that can be universally agreed upon. I suggest that you define the rule in your `g:easy_align_delimiters` like so in your Vim configuration file.

```vim
let g:easy_align_delimiters = { ';': { 'pattern': ';', 'left_margin': 1, 'right_margin': 0, 'stick_to_left': 0 } }
```

**Pull request closed without merging**
